##
## EPITECH PROJECT, 2023
## B-YEP-400-NCY-4-1-zappy-antoine.khalidy
## File description:
## Makefile
##

all:
	make -C unitary_test

clean:
	make clean -C unitary_test

fclean:
	make fclean -C unitary_test

re:
	make re -C unitary_test

.PHONY: all clean fclean re
